pipeline {
  agent any 
    tools {
       //Installed the maven version configured as 'M3' and add it to the path
     jdk 'Java'
     maven 'Maven'
  }
  
  stages 
  {
   stage('checkout') {
     steps {
       // get some code from a GitHub repository
       git 'https://github.com/madhupriya1121/game-of-life.git'
    }
  }
  stage('compile and build') {
      steps {
          sh '''
          mvn clean install -U -Dmaven.skip.test=true
          '''
      }
  }
}
}
